user authentication framework
shokoladber/group-michael-2 pull request #6
Opened 2024-01-22 22:14 UTC by lucydames

2024-01-25 00:05 UTC, joann37 approved these changes

2024-01-28 18:17 UTC, erinsuzy approved these changes

2024-01-29 23:04 UTC, erinsuzy requested changes
I have a possible fix for the issue with the Javax.servlet filter error that is showing up. Apparently, with the new SpringBoot, we can't have any Javax, it has to be all Jakarta and WebSecurityConfigurerAdapter is now out-of-date. I saw a fix on Stack Overflow that may help. 
https://stackoverflow.com/questions/74982010/spring-security-cannot-access-javax-servlet-filter

2024-01-30 05:28 UTC, lucydames commented
Yes, this is actually the article that helped me fix it. I did get this
updated fully to jakarta and using SecurityFilterChain. Thanks!

On Mon, Jan 29, 2024 at 5:05 PM erinsuzy ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> I have a possible fix for the issue with the Javax.servlet filter error
> that is showing up. Apparently, with the new SpringBoot, we can't have any
> Javax, it has to be all Jakarta and WebSecurityConfigurerAdapter is now
> out-of-date. I saw a fix on Stack Overflow that may help.
>
> https://stackoverflow.com/questions/74982010/spring-security-cannot-access-javax-servlet-filter
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/shokoladber/group-michael-2/pull/6#pullrequestreview-1849935846>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BAMPNBIT7BBVRJHGTY2RY2DYRATJ5AVCNFSM6AAAAABCF6NO4WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNBZHEZTKOBUGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-31 02:43 UTC, closed without merging